### ISSUE TITLE
Use of `acknowledge_request`

### ISSUE THREAD

**Issue by demberto** [oluan/ninjaipc#1]
```cpp
int main() {
    ninjaipc::ninjahandle ipc = ninjaipc::connect("ninjaipc");
    std::filesystem::path* path;

    ninjaipc::listen(ipc, [ipc, path](void* request) -> void {
        auto str = reinterpret_cast<char*>(request);
        if (str == "CLOSE") // wb acknowledge_request here?
            return;

        *path = std::filesystem::path(str);
        ninjaipc::acknowledge_request(ipc);
    });
}
```

This is my client. It will repeat until instructed to `CLOSE`. I don't really understand how to return the exit code from the call back and whether I need to call `acknowledge_request` there too.

Btw, yours is the simplest IPC library out there. I will star it if it works out for me. Also I need to send a message back from the client to the server, do I need to do it in the callback or it can be done below?

**Comment by oluan** [comment]
Hi, @demberto.

NinjaIPC is currently being rewritten to fit multiple languages.

The C++ interface will remain as simple as always, the project currently doesn't have a proper documentation (what will change in the near future.)

About your question:

you'll use either `acknowledge_request` or `respond` or `respond_text`. (all action you will want to do inside callback (but doesn't really matter as long as you call any of these three functions after callback)

these three functions will either clear the buffer and notify server that the request is over or respond the server and notify that the request is over.

btw,

```cpp
if (str == "CLOSE") // <-- invalid string comparation in C++
  return;
```

should be

```cpp
if (std::string(str) == "CLOSE")
  return;
```

or strcmp...

**Comment by oluan** [comment]
Feel free to check the new C++ api!
