### ISSUE TITLE
No way to close a `ninjahandle`

### ISSUE THREAD

**Issue by demberto** [oluan/ninjaipc#2]
If an application fails to execute properly and terminates, NinjaIPC doesn't close the created shared memory object nor provides a method to do the same. The only way to solve it afaik is restarting the PC. Not good :(

**Comment by oluan** [comment]
@demberto the next version of ninjaipc C++ wrapper will have that option, thanks.

**Comment by oluan** [comment]
You can now free IPC objects and primitives.
